spring:
  application:
    name: API-GATEWAY

server:
  port: 8760

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    order-service:
       path: /orders/**
       serviceId: ORDER-SERVICE
    user-service:
       path: /users/**
       serviceId: USER-SERVICE
    product-service:
       path: /products/**
       serviceId: PRODUCT-SERVICE
  host:
    socket-timeout-millis: 30000       